name: Build and Test ASFA

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  buildntest:
    name: Build and test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permissions to Npmw wrapper
        run: chmod +x ./npmw

      - name: Install Frontend Dependencies
        run: |
          ./npmw install
          ./npmw run build --if-present

      - name: Grant execute permissions to Maven wrapper
        run: chmod +x ./mvnw

      - name: Build and Test Backend
        run: |
          ./mvnw clean verify -Pprod -X -e

      - name: Test frontend
        run: ./npmw run webapp:test

      - name: Archive target
        uses: actions/upload-artifact@v4
        with:
          name: archiveTarget
          path: target/

  sonar:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest
    needs: buildntest # This ensures the sonar job waits for buildntest to complete

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarQube analysis

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: archiveTarget
          path: target/

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
