name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions to Maven wrapper
        run: chmod +x ./mvnw

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "spacecowboy72" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: spacecowboy72
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          ./mvnw package -Pprod verify jib:build \
            -Djib.to.image=docker.io/spacecowboy72/asfa:latest \
            -Djib.to.auth.username=spacecowboy72 \
            -Djib.to.auth.password=${{ secrets.DOCKER_TOKEN }}
